title: Serratus
description: >-
  TODO: Write description here.
baseurl: "/serratus.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.19.2"
plugins:
  - jekyll-feed
  - jekyll-include-cache
